#!/bin/sh
# affiche uniquement l'interface awdl0 (qui correspond à la carte wifi) 
# affiche chaques bloc n.2 contenant "ether" car cela repressente l'adresse MAC
ifconfig awdl0 | awk '/ether/ {print $2}'
