#!/bin/sh
# affiche tout les IP correspondant au DNS slash16.org en passant par le serveur 8.8.8.8 (google.com)
# recupere ensuite toute les lignes contenant "has address" (traitement)
# affiche uniquement le 4eme bloc de chaques lignes
# IDEM "host slash16.org 8.8.8.8 | awk '/has address/ {print $4}'"
dig slash16.org @8.8.8.8 +short
